# Generated by Django 4.1.7 on 2023-02-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0003_ticket_assigned_on_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_on',
            field=models.DateTimeField(null=True),
        ),
    ]
