# Generated by Django 4.1.7 on 2023-03-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0008_remove_notification_ticket_notification_by_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='by_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets_app.ticket'),
        ),
    ]
