# Generated by Django 4.1.7 on 2023-03-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0009_alter_notification_by_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='feedback',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
