# Generated by Django 4.1.7 on 2023-03-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0011_notification_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
