# Generated by Django 4.1.7 on 2023-03-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_app', '0013_alter_ticket_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='feedback',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='uploads/'),
        ),
    ]
